/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Данные по файлам архива
    /// </summary>
    [DataContract]
    public partial class ArchiveFileInfo : IEquatable<ArchiveFileInfo>
    { 
        /// <summary>
        /// Gets or Sets OriginalArchiveFile
        /// </summary>

        [DataMember(Name="originalArchiveFile")]
        public ArchiveFileDto OriginalArchiveFile { get; set; }

        /// <summary>
        /// Gets or Sets UnrecognizedArchiveFile
        /// </summary>

        [DataMember(Name="unrecognizedArchiveFile")]
        public ArchiveFileDto UnrecognizedArchiveFile { get; set; }

        /// <summary>
        /// Gets or Sets AgreementArchiveFile
        /// </summary>

        [DataMember(Name="agreementArchiveFile")]
        public ArchiveFileDto AgreementArchiveFile { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArchiveFileInfo {\n");
            sb.Append("  OriginalArchiveFile: ").Append(OriginalArchiveFile).Append("\n");
            sb.Append("  UnrecognizedArchiveFile: ").Append(UnrecognizedArchiveFile).Append("\n");
            sb.Append("  AgreementArchiveFile: ").Append(AgreementArchiveFile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ArchiveFileInfo)obj);
        }

        /// <summary>
        /// Returns true if ArchiveFileInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of ArchiveFileInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArchiveFileInfo other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OriginalArchiveFile == other.OriginalArchiveFile ||
                    OriginalArchiveFile != null &&
                    OriginalArchiveFile.Equals(other.OriginalArchiveFile)
                ) && 
                (
                    UnrecognizedArchiveFile == other.UnrecognizedArchiveFile ||
                    UnrecognizedArchiveFile != null &&
                    UnrecognizedArchiveFile.Equals(other.UnrecognizedArchiveFile)
                ) && 
                (
                    AgreementArchiveFile == other.AgreementArchiveFile ||
                    AgreementArchiveFile != null &&
                    AgreementArchiveFile.Equals(other.AgreementArchiveFile)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OriginalArchiveFile != null)
                    hashCode = hashCode * 59 + OriginalArchiveFile.GetHashCode();
                    if (UnrecognizedArchiveFile != null)
                    hashCode = hashCode * 59 + UnrecognizedArchiveFile.GetHashCode();
                    if (AgreementArchiveFile != null)
                    hashCode = hashCode * 59 + AgreementArchiveFile.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ArchiveFileInfo left, ArchiveFileInfo right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ArchiveFileInfo left, ArchiveFileInfo right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
