/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Идентификационные данные пользователя
    /// </summary>
    [DataContract]
    public partial class ClientIdentity : IEquatable<ClientIdentity>
    { 
        /// <summary>
        /// Идентификатор клиента
        /// </summary>
        /// <value>Идентификатор клиента</value>

        [MaxLength(255)]
        [DataMember(Name="clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// Признак мастер-клиента
        /// </summary>
        /// <value>Признак мастер-клиента</value>

        [DataMember(Name="isMaster")]
        public bool? IsMaster { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClientIdentity {\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  IsMaster: ").Append(IsMaster).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ClientIdentity)obj);
        }

        /// <summary>
        /// Returns true if ClientIdentity instances are equal
        /// </summary>
        /// <param name="other">Instance of ClientIdentity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClientIdentity other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ClientId == other.ClientId ||
                    ClientId != null &&
                    ClientId.Equals(other.ClientId)
                ) && 
                (
                    IsMaster == other.IsMaster ||
                    IsMaster != null &&
                    IsMaster.Equals(other.IsMaster)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ClientId != null)
                    hashCode = hashCode * 59 + ClientId.GetHashCode();
                    if (IsMaster != null)
                    hashCode = hashCode * 59 + IsMaster.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ClientIdentity left, ClientIdentity right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ClientIdentity left, ClientIdentity right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
