/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Данные элемента
    /// </summary>
    [DataContract]
    public partial class FieldPropertyHeaderDto : IEquatable<FieldPropertyHeaderDto>
    { 
        /// <summary>
        /// Заголовок элемента
        /// </summary>
        /// <value>Заголовок элемента</value>

        [MaxLength(255)]
        [DataMember(Name="label")]
        public string Label { get; set; }

        /// <summary>
        /// Ссылка на код дочернего поля
        /// </summary>
        /// <value>Ссылка на код дочернего поля</value>

        [MaxLength(255)]
        [DataMember(Name="field")]
        public string Field { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FieldPropertyHeaderDto {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FieldPropertyHeaderDto)obj);
        }

        /// <summary>
        /// Returns true if FieldPropertyHeaderDto instances are equal
        /// </summary>
        /// <param name="other">Instance of FieldPropertyHeaderDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FieldPropertyHeaderDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Label == other.Label ||
                    Label != null &&
                    Label.Equals(other.Label)
                ) && 
                (
                    Field == other.Field ||
                    Field != null &&
                    Field.Equals(other.Field)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Label != null)
                    hashCode = hashCode * 59 + Label.GetHashCode();
                    if (Field != null)
                    hashCode = hashCode * 59 + Field.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FieldPropertyHeaderDto left, FieldPropertyHeaderDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FieldPropertyHeaderDto left, FieldPropertyHeaderDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
