/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Данные вложений
    /// </summary>
    [DataContract]
    public partial class FnsAnnexDto : IEquatable<FnsAnnexDto>
    { 
        /// <summary>
        /// Данные о частях файлов-вложений
        /// </summary>
        /// <value>Данные о частях файлов-вложений</value>

        [DataMember(Name="parts")]
        public List<FilePartDto> Parts { get; set; }

        /// <summary>
        /// Формат файла
        /// </summary>
        /// <value>Формат файла</value>

        [MaxLength(255)]
        [DataMember(Name="format")]
        public string Format { get; set; }

        /// <summary>
        /// Тип файла вложения
        /// </summary>
        /// <value>Тип файла вложения</value>

        [MaxLength(255)]
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// Признак того, что файл получен при распознавании архива.
        /// </summary>
        /// <value>Признак того, что файл получен при распознавании архива.</value>

        [DataMember(Name="fromArchive")]
        public bool? FromArchive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FnsAnnexDto {\n");
            sb.Append("  Parts: ").Append(Parts).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  FromArchive: ").Append(FromArchive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FnsAnnexDto)obj);
        }

        /// <summary>
        /// Returns true if FnsAnnexDto instances are equal
        /// </summary>
        /// <param name="other">Instance of FnsAnnexDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FnsAnnexDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Parts == other.Parts ||
                    Parts != null &&
                    Parts.SequenceEqual(other.Parts)
                ) && 
                (
                    Format == other.Format ||
                    Format != null &&
                    Format.Equals(other.Format)
                ) && 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    FromArchive == other.FromArchive ||
                    FromArchive != null &&
                    FromArchive.Equals(other.FromArchive)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Parts != null)
                    hashCode = hashCode * 59 + Parts.GetHashCode();
                    if (Format != null)
                    hashCode = hashCode * 59 + Format.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (FromArchive != null)
                    hashCode = hashCode * 59 + FromArchive.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FnsAnnexDto left, FnsAnnexDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FnsAnnexDto left, FnsAnnexDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
