/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Значения продукта найденные в DRP
    /// </summary>
    [DataContract]
    public partial class FoundProductResponseEditDto : IEquatable<FoundProductResponseEditDto>
    { 
        /// <summary>
        /// Значение продукта из витрин
        /// </summary>
        /// <value>Значение продукта из витрин</value>

        [MaxLength(255)]
        [DataMember(Name="value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets Archive
        /// </summary>

        [DataMember(Name="archive")]
        public ArchiveDto Archive { get; set; }

        /// <summary>
        /// Данные вложений
        /// </summary>
        /// <value>Данные вложений</value>

        [DataMember(Name="annexes")]
        public List<AnnexDto> Annexes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FoundProductResponseEditDto {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Archive: ").Append(Archive).Append("\n");
            sb.Append("  Annexes: ").Append(Annexes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FoundProductResponseEditDto)obj);
        }

        /// <summary>
        /// Returns true if FoundProductResponseEditDto instances are equal
        /// </summary>
        /// <param name="other">Instance of FoundProductResponseEditDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FoundProductResponseEditDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Value == other.Value ||
                    Value != null &&
                    Value.Equals(other.Value)
                ) && 
                (
                    Archive == other.Archive ||
                    Archive != null &&
                    Archive.Equals(other.Archive)
                ) && 
                (
                    Annexes == other.Annexes ||
                    Annexes != null &&
                    Annexes.SequenceEqual(other.Annexes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (Archive != null)
                    hashCode = hashCode * 59 + Archive.GetHashCode();
                    if (Annexes != null)
                    hashCode = hashCode * 59 + Annexes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FoundProductResponseEditDto left, FoundProductResponseEditDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FoundProductResponseEditDto left, FoundProductResponseEditDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
