/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Задача идентификации клиента
    /// </summary>
    [DataContract]
    public partial class IdentificationTaskDto : IEquatable<IdentificationTaskDto>
    { 
        /// <summary>
        /// Регистрационный номер запроса, присвоенный в СДО
        /// </summary>
        /// <value>Регистрационный номер запроса, присвоенный в СДО</value>

        [MaxLength(255)]
        [DataMember(Name="regNumber")]
        public string RegNumber { get; set; }

        /// <summary>
        /// Дата подачи запроса ФОИВ
        /// </summary>
        /// <value>Дата подачи запроса ФОИВ</value>

        [DataMember(Name="regDate")]
        public DateTime? RegDate { get; set; }

        /// <summary>
        /// Подсказка
        /// </summary>
        /// <value>Подсказка</value>

        [MaxLength(1024)]
        [DataMember(Name="hint")]
        public string Hint { get; set; }

        /// <summary>
        /// Срок выполнения запроса
        /// </summary>
        /// <value>Срок выполнения запроса</value>

        [DataMember(Name="dueDate")]
        public DateTime? DueDate { get; set; }

        /// <summary>
        /// Gets or Sets InputRequestClientData
        /// </summary>

        [DataMember(Name="inputRequestClientData")]
        public IdentificationTargetDto InputRequestClientData { get; set; }

        /// <summary>
        /// Клиенты (Озеро)
        /// </summary>
        /// <value>Клиенты (Озеро)</value>

        [DataMember(Name="drpClientsData")]
        public List<DrpClientDataDto> DrpClientsData { get; set; }

        /// <summary>
        /// Клиенты (Карточка Клиентов)
        /// </summary>
        /// <value>Клиенты (Карточка Клиентов)</value>

        [DataMember(Name="csClientsData")]
        public List<CsClientDataDto> CsClientsData { get; set; }

        /// <summary>
        /// Флаг показа элемента UI с данными о файловой шаре
        /// </summary>
        /// <value>Флаг показа элемента UI с данными о файловой шаре</value>

        [DataMember(Name="showOriginalRequestButton")]
        public bool? ShowOriginalRequestButton { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IdentificationTaskDto {\n");
            sb.Append("  RegNumber: ").Append(RegNumber).Append("\n");
            sb.Append("  RegDate: ").Append(RegDate).Append("\n");
            sb.Append("  Hint: ").Append(Hint).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  InputRequestClientData: ").Append(InputRequestClientData).Append("\n");
            sb.Append("  DrpClientsData: ").Append(DrpClientsData).Append("\n");
            sb.Append("  CsClientsData: ").Append(CsClientsData).Append("\n");
            sb.Append("  ShowOriginalRequestButton: ").Append(ShowOriginalRequestButton).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((IdentificationTaskDto)obj);
        }

        /// <summary>
        /// Returns true if IdentificationTaskDto instances are equal
        /// </summary>
        /// <param name="other">Instance of IdentificationTaskDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IdentificationTaskDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    RegNumber == other.RegNumber ||
                    RegNumber != null &&
                    RegNumber.Equals(other.RegNumber)
                ) && 
                (
                    RegDate == other.RegDate ||
                    RegDate != null &&
                    RegDate.Equals(other.RegDate)
                ) && 
                (
                    Hint == other.Hint ||
                    Hint != null &&
                    Hint.Equals(other.Hint)
                ) && 
                (
                    DueDate == other.DueDate ||
                    DueDate != null &&
                    DueDate.Equals(other.DueDate)
                ) && 
                (
                    InputRequestClientData == other.InputRequestClientData ||
                    InputRequestClientData != null &&
                    InputRequestClientData.Equals(other.InputRequestClientData)
                ) && 
                (
                    DrpClientsData == other.DrpClientsData ||
                    DrpClientsData != null &&
                    DrpClientsData.SequenceEqual(other.DrpClientsData)
                ) && 
                (
                    CsClientsData == other.CsClientsData ||
                    CsClientsData != null &&
                    CsClientsData.SequenceEqual(other.CsClientsData)
                ) && 
                (
                    ShowOriginalRequestButton == other.ShowOriginalRequestButton ||
                    ShowOriginalRequestButton != null &&
                    ShowOriginalRequestButton.Equals(other.ShowOriginalRequestButton)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (RegNumber != null)
                    hashCode = hashCode * 59 + RegNumber.GetHashCode();
                    if (RegDate != null)
                    hashCode = hashCode * 59 + RegDate.GetHashCode();
                    if (Hint != null)
                    hashCode = hashCode * 59 + Hint.GetHashCode();
                    if (DueDate != null)
                    hashCode = hashCode * 59 + DueDate.GetHashCode();
                    if (InputRequestClientData != null)
                    hashCode = hashCode * 59 + InputRequestClientData.GetHashCode();
                    if (DrpClientsData != null)
                    hashCode = hashCode * 59 + DrpClientsData.GetHashCode();
                    if (CsClientsData != null)
                    hashCode = hashCode * 59 + CsClientsData.GetHashCode();
                    if (ShowOriginalRequestButton != null)
                    hashCode = hashCode * 59 + ShowOriginalRequestButton.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(IdentificationTaskDto left, IdentificationTaskDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(IdentificationTaskDto left, IdentificationTaskDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
