/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Продукт
    /// </summary>
    [DataContract]
    public partial class ProductResponseEditDto : IEquatable<ProductResponseEditDto>
    { 
        /// <summary>
        /// Идентификатор продукта
        /// </summary>
        /// <value>Идентификатор продукта</value>
        [RegularExpression("/\\b[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}\\b/")]
        [MaxLength(36)]
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ProductType
        /// </summary>

        [DataMember(Name="productType")]
        public DictionaryItem ProductType { get; set; }

        /// <summary>
        /// Значение продукта из запроса ФОИВ
        /// </summary>
        /// <value>Значение продукта из запроса ФОИВ</value>

        [MaxLength(255)]
        [DataMember(Name="value")]
        public string Value { get; set; }

        /// <summary>
        /// Значения продукта найденные в DRP
        /// </summary>
        /// <value>Значения продукта найденные в DRP</value>

        [DataMember(Name="foundProducts")]
        public List<FoundProductResponseEditDto> FoundProducts { get; set; }

        /// <summary>
        /// Gets or Sets Attribute
        /// </summary>

        [DataMember(Name="attribute")]
        public AttributeResponseEditDto Attribute { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductResponseEditDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ProductType: ").Append(ProductType).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  FoundProducts: ").Append(FoundProducts).Append("\n");
            sb.Append("  Attribute: ").Append(Attribute).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductResponseEditDto)obj);
        }

        /// <summary>
        /// Returns true if ProductResponseEditDto instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductResponseEditDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductResponseEditDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    ProductType == other.ProductType ||
                    ProductType != null &&
                    ProductType.Equals(other.ProductType)
                ) && 
                (
                    Value == other.Value ||
                    Value != null &&
                    Value.Equals(other.Value)
                ) && 
                (
                    FoundProducts == other.FoundProducts ||
                    FoundProducts != null &&
                    FoundProducts.SequenceEqual(other.FoundProducts)
                ) && 
                (
                    Attribute == other.Attribute ||
                    Attribute != null &&
                    Attribute.Equals(other.Attribute)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (ProductType != null)
                    hashCode = hashCode * 59 + ProductType.GetHashCode();
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (FoundProducts != null)
                    hashCode = hashCode * 59 + FoundProducts.GetHashCode();
                    if (Attribute != null)
                    hashCode = hashCode * 59 + Attribute.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductResponseEditDto left, ProductResponseEditDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductResponseEditDto left, ProductResponseEditDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
