/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Данные созданного каталога в файловом хранилище
    /// </summary>
    [DataContract]
    public partial class SharedDirectory : IEquatable<SharedDirectory>
    { 
        /// <summary>
        /// Путь созданного каталога в файловом хранилище
        /// </summary>
        /// <value>Путь созданного каталога в файловом хранилище</value>

        [MaxLength(255)]
        [DataMember(Name="path")]
        public string Path { get; set; }

        /// <summary>
        /// Отметка о создании каталога
        /// </summary>
        /// <value>Отметка о создании каталога</value>

        [DataMember(Name="isCreated")]
        public bool? IsCreated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SharedDirectory {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  IsCreated: ").Append(IsCreated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SharedDirectory)obj);
        }

        /// <summary>
        /// Returns true if SharedDirectory instances are equal
        /// </summary>
        /// <param name="other">Instance of SharedDirectory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SharedDirectory other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Path == other.Path ||
                    Path != null &&
                    Path.Equals(other.Path)
                ) && 
                (
                    IsCreated == other.IsCreated ||
                    IsCreated != null &&
                    IsCreated.Equals(other.IsCreated)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Path != null)
                    hashCode = hashCode * 59 + Path.GetHashCode();
                    if (IsCreated != null)
                    hashCode = hashCode * 59 + IsCreated.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SharedDirectory left, SharedDirectory right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SharedDirectory left, SharedDirectory right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
