/*
 * 81_1.CNTS_PTZP-ErmTask-s-rest-v2
 *
 * ERM API provider
 *
 * OpenAPI spec version: 3.0.0
 * Contact: kakolesov@vtb.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Валидация поля
    /// </summary>
    [DataContract]
    public partial class ValidationInfoDto : IEquatable<ValidationInfoDto>
    { 
        /// <summary>
        /// Регулярное выражения для валиации поля
        /// </summary>
        /// <value>Регулярное выражения для валиации поля</value>

        [MaxLength(255)]
        [DataMember(Name="regexp")]
        public string Regexp { get; set; }

        /// <summary>
        /// Текст с ошибкой валидации поля
        /// </summary>
        /// <value>Текст с ошибкой валидации поля</value>

        [MaxLength(255)]
        [DataMember(Name="validationMessage")]
        public string ValidationMessage { get; set; }

        /// <summary>
        /// Признак обязательности поля
        /// </summary>
        /// <value>Признак обязательности поля</value>

        [DataMember(Name="isRequired")]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValidationInfoDto {\n");
            sb.Append("  Regexp: ").Append(Regexp).Append("\n");
            sb.Append("  ValidationMessage: ").Append(ValidationMessage).Append("\n");
            sb.Append("  IsRequired: ").Append(IsRequired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ValidationInfoDto)obj);
        }

        /// <summary>
        /// Returns true if ValidationInfoDto instances are equal
        /// </summary>
        /// <param name="other">Instance of ValidationInfoDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValidationInfoDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Regexp == other.Regexp ||
                    Regexp != null &&
                    Regexp.Equals(other.Regexp)
                ) && 
                (
                    ValidationMessage == other.ValidationMessage ||
                    ValidationMessage != null &&
                    ValidationMessage.Equals(other.ValidationMessage)
                ) && 
                (
                    IsRequired == other.IsRequired ||
                    IsRequired != null &&
                    IsRequired.Equals(other.IsRequired)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Regexp != null)
                    hashCode = hashCode * 59 + Regexp.GetHashCode();
                    if (ValidationMessage != null)
                    hashCode = hashCode * 59 + ValidationMessage.GetHashCode();
                    if (IsRequired != null)
                    hashCode = hashCode * 59 + IsRequired.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ValidationInfoDto left, ValidationInfoDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ValidationInfoDto left, ValidationInfoDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
